# Generated by Django 5.0.4 on 2024-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="Task",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
